version:  '3.7'
services:
    mysql_db:
        image: mysql:8.0
        container_name: tr-mysql
        ports:
          - 3366:3306
        restart: on-failure
        command: --default-authentication-plugin=mysql_native_password --sql_mode=""
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: tr

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: tr-phpmyadmin
        links:
            - mysql_db
        environment:
            PMA_HOST: mysql_db
            PMA_PORT: 3306
            PMA_USER: root
            PMA_PASSWORD: root
        ports:
            - '9898:80'

    nginx:
        image: nginx:1.15.3-alpine
        container_name: tr-nginx
        restart: on-failure
        volumes:
            - './public/:/usr/src/app'
            - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
        ports:
            - '8989:80'
        depends_on:
            - php

    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        restart: on-failure
        container_name: tr-php
        volumes:
            - './:/usr/src/app'